apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: prometheus-istio-destinationrule
  namespace: istio-system
spec:
  host: prometheus
  trafficPolicy:
    tls:
      mode: DISABLE
